
package main;

import d.dashboard;
import config.DBC;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import javafx.scene.paint.Color;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.sql.*;



public class panel extends javax.swing.JFrame {

    /**
     * Creates new form panel
     */
    public panel() {
        initComponents();
        
        // 1. Setup the initial look
    username.setText("Enter Username...");
    

    // 2. Add the Listener
    username.addFocusListener(new FocusListener() {
        @Override
        public void focusGained(FocusEvent e) {
            // IF text is the placeholder, clear it
            if (username.getText().equals("Enter Username...")) {
                username.setText("");
              
            }
        }

        @Override
        public void focusLost(FocusEvent e) {
            // IF user didn't type anything, put the placeholder back
            if (username.getText().isEmpty()) {
                username.setText("Enter Username...");
               
            }
        }

   
    });
    String pass = String.valueOf(password.getPassword());


    setSize(750, 500); 
    
    // 2. Center it
    setLocationRelativeTo(null);
    
    password.setEchoChar((char)0); // Make visible
password.setText("Enter Password");
password.setForeground(new java.awt.Color(153, 153, 153)); // Gray

// 2. Add the listener manually
password.addFocusListener(new java.awt.event.FocusAdapter() {
    
    // WHEN CLICKED
    public void focusGained(java.awt.event.FocusEvent evt) {
        String pass = String.valueOf(password.getPassword());
        if (pass.equals("Enter Password")) {
            password.setText("");
            password.setForeground(java.awt.Color.BLACK);
            password.setEchoChar('*'); // Hide password
        }
    }

    // WHEN LEFT
    public void focusLost(java.awt.event.FocusEvent evt) {
        String pass = String.valueOf(password.getPassword());
        if (pass.length() == 0 || pass.equals("")) {
            password.setText("Enter Password");
            password.setForeground(new java.awt.Color(153, 153, 153));
            password.setEchoChar((char)0); // Show text
        }
    }
});

    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setAutoscrolls(true);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setLabelFor(this);
        jLabel1.setText("Bike shop");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 140, 40));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 770, 70);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        username.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        username.setText("Enter name");
        username.setDragEnabled(true);
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        jPanel2.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 200, 30));

        password.setText("jPasswordField1");
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        jPanel2.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 200, 30));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("log in");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jLabel2MouseWheelMoved(evt);
            }
        });
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 34, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("register");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 50, 20));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("welcome too bike shop");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 380, 110));

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 70, 770, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void jLabel2MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jLabel2MouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseWheelMoved

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
// 1. GET INPUTS & REMOVE SPACES
String u = username.getText().trim(); // .trim() removes accidental spaces
String p = String.valueOf(password.getPassword()).trim();

// --- STRICT VALIDATION: CHECK IF EMPTY ---
if (u.equals("") || p.equals("")) {
    // Show Error Message
    javax.swing.JOptionPane.showMessageDialog(this, 
        "Username and Password are required!", 
        "Validation Error", 
        javax.swing.JOptionPane.ERROR_MESSAGE);
    
    // STOP THE CODE HERE. Do not proceed to database.
    return; 
}

// --- IF NOT EMPTY, PROCEED TO DATABASE CHECK ---
try {
    java.sql.Connection con = config.DBC.connectDB();
    
    // Check if user exists
    String sql = "SELECT * FROM Tbl_user WHERE username = ? AND password = ?";
    java.sql.PreparedStatement pst = con.prepareStatement(sql);
    pst.setString(1, u);
    pst.setString(2, p);
    
    java.sql.ResultSet rs = pst.executeQuery();

    if (rs.next()) {
        // --- LOGIN SUCCESS ---
        
        // Get Role safely
        String dbRole = rs.getString("role");
        if(dbRole == null || dbRole.isEmpty()) dbRole = "user";

        // Save to Global Config
        config.DBC.username = rs.getString("username");
        config.DBC.email = rs.getString("email");
        config.DBC.role = dbRole;

        System.out.println("Login Success: " + u + " (" + dbRole + ")");

        // Open Loading Screen
        loading load = new loading(dbRole); 
        load.setVisible(true);
        this.dispose(); // Close Login
        
    } else {
        // --- LOGIN FAILED ---
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Invalid Username or Password!", 
            "Access Denied", 
            javax.swing.JOptionPane.WARNING_MESSAGE);
    }
    
    rs.close(); pst.close(); con.close();

} catch (Exception e) {
    javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
}
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
         loading load = new loading("landng");
        load.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
// 1. GET INPUTS
String u = username.getText();
String p = String.valueOf(password.getPassword());

// --- VALIDATION 1: CHECK FOR EMPTY FIELDS ---
if(u.trim().isEmpty() || p.trim().isEmpty()) {
    javax.swing.JOptionPane.showMessageDialog(this, 
        "Username and Password cannot be empty!", 
        "Input Error", 
        javax.swing.JOptionPane.ERROR_MESSAGE);
    return; // Stop the code here
}

try {
    // 2. CONNECT TO DATABASE
    java.sql.Connection con = config.DBC.connectDB();
    
    // Use PreparedStatement to prevent errors and hacking
    String sql = "SELECT * FROM Tbl_user WHERE username = ? AND password = ?";
    java.sql.PreparedStatement pst = con.prepareStatement(sql);
    pst.setString(1, u);
    pst.setString(2, p);
    
    java.sql.ResultSet rs = pst.executeQuery();

    // --- VALIDATION 2: CHECK IF USER EXISTS ---
    if (rs.next()) {
        // LOGIN SUCCESS!
        
        // 3. GET DATA FROM DATABASE
        String dbRole = rs.getString("role");
        
        // Safety: If role is empty in DB, default to "user"
        if (dbRole == null || dbRole.trim().isEmpty()) {
            dbRole = "user";
        }

        // 4. SAVE TO GLOBAL VARIABLES (DBC)
        config.DBC.username = rs.getString("username");
        config.DBC.email = rs.getString("email");
        config.DBC.role = dbRole;
        // config.DBC.id = rs.getInt("u_id"); // Uncomment if you added 'id' to DBC

        // 5. SUCCESS MESSAGE
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Login Successful! Welcome " + config.DBC.username, 
            "Success", 
            javax.swing.JOptionPane.INFORMATION_MESSAGE);

        // 6. OPEN LOADING SCREEN (Pass the role)
        loading load = new loading(dbRole); 
        load.setVisible(true);
        this.dispose(); // Close Login Window
        
    } else {
        // LOGIN FAILED (Invalid Username/Password)
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Invalid Username or Password. Please try again.", 
            "Login Failed", 
            javax.swing.JOptionPane.WARNING_MESSAGE);
    }
    
    // Close connections
    rs.close();
    pst.close();
    con.close();

} catch (Exception e) {
    // SYSTEM ERROR (Database connection failed, etc.)
    javax.swing.JOptionPane.showMessageDialog(this, 
        "System Error: " + e.getMessage(), 
        "Error", 
        javax.swing.JOptionPane.ERROR_MESSAGE);
    System.out.println("Login Error: " + e);
}
    }//GEN-LAST:event_jPanel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new panel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
